### ISSUE TITLE
Bracket Highlighter does not work well with theme Centurion ???

### ISSUE THREAD

**Issue by qeesung** [allanhortle/Centurion#30]
Centurion  is my favorite sublime theme .But my "Bracket Highlighter" Plug-in unit does not work well when I switched to the Centurion theme.Is this a Bug?How can fix that?

**Comment by allanhortle** [comment]
What specifically is not working? I just installed the plugin and I'm getting most features. No colors though. A screen shot of what it should be vs what it's like with Centurion would be helpful.

**Comment by druellan** [comment]
I'm using Centurion with Bracket Highlighter for some time now, and I didn't see a problem. No colors, but I believe this is related to the color syntax (Galea), not the theme.

**Comment by allanhortle** [comment]
Closing as it appears to work fine.
![image](https://cloud.githubusercontent.com/assets/3760524/25785731/1bad2a70-33cb-11e7-8ed3-cebb30246436.png)
