### ISSUE TITLE
Going back to default theme

### ISSUE THREAD

**Issue by Karthik248** [allanhortle/Centurion#32]
Centurion installed   with green as default color, but after i try other color using the preference `"centurion_color_xxx": true` , i'm unable to go back to the green color with `"centurion_color_green": true`.
Am i missing something?

Thanks in advance.

P.S: I really love the green flavor :)

**Comment by allanhortle** [comment]
Hey did you get this sorted out?

**Comment by Karthik248** [comment]
yes, i'm not sure about this, i added these to the settings..
```
"centurion_color_blue": false,
"centurion_color_red": false,
"centurion_color_yellow": false,
"centurion_color_orange": false,
"centurion_color_grey": false
```
and it worked out.
