### ISSUE TITLE
Highlighting color in command palette same as background

### ISSUE THREAD

**Issue by lorenzschmid** [allanhortle/Centurion#33]
When opening up the command palette (`Cmd + Shift + P`) in Sublime Text 3, the highlighting color of the fuzzy search seems to be the same than the backround of the command palette. And thus becomes invisible:

![centurion_bug](https://user-images.githubusercontent.com/3830671/47225017-4aae0b80-d3bd-11e8-8a00-0818a342a58d.PNG)

**Comment by allanhortle** [comment]
Sorry for the delay @lorenzschmid. This should be fixed in: https://github.com/allanhortle/Centurion/releases/tag/v2.3.1
